### Bài 3.1


In [1]:
import numpy as np
print("Numpy version:", np.__version__)
np.show_config()

Numpy version: 2.0.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vclkdodh/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### Bài 3.2

In [2]:
import numpy as np

# 1. Tạo numpy array arr có 6 phần tử từ 0-9
arr = np.random.randint(0, 10, size=6)
print("Array arr:", arr)
print("Kiểu dữ liệu của arr:", arr.dtype)
print("Kích thước của arr:", arr.shape)

# 2. Tạo arr_even gồm các phần tử chẵn trong arr
arr_even = arr[arr % 2 == 0]
print("Array arr_even (phần tử chẵn):", arr_even)

# 3. Tạo arr_odd gồm các phần tử lẻ trong arr
arr_odd = arr[arr % 2 != 0]
print("Array arr_odd (phần tử lẻ):", arr_odd)

# 4. Tạo arr_update từ arr với các phần tử lẻ thay bằng 100
arr_update = np.where(arr % 2 == 0, arr, 100)
print("Array arr_update (phần tử lẻ thay bằng 100):", arr_update)



Array arr: [4 0 0 0 2 2]
Kiểu dữ liệu của arr: int32
Kích thước của arr: (6,)
Array arr_even (phần tử chẵn): [4 0 0 0 2 2]
Array arr_odd (phần tử lẻ): []
Array arr_update (phần tử lẻ thay bằng 100): [4 0 0 0 2 2]


### Bài 3.3

In [3]:
import numpy as np
arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# 1. Tạo arr_c chỉ chứa các phần tử xuất hiện ở cả arr_a và arr_b
arr_c = np.intersect1d(arr_a, arr_b)
print("Array arr_c (các phần tử chung của arr_a và arr_b):", arr_c)

# 2. Tạo arr_d chứa các phần tử chỉ xuất hiện ở arr_a
arr_d = np.setdiff1d(arr_a, arr_b)
print("Array arr_d (các phần tử chỉ xuất hiện ở arr_a):", arr_d)

# 3. Tạo arr_f chỉ chứa các phần tử có giá trị từ 5 đến 10 của arr_e
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print("Array arr_f (các phần tử có giá trị từ 5 đến 10 của arr_e):", arr_f)

Array arr_c (các phần tử chung của arr_a và arr_b): [2 4]
Array arr_d (các phần tử chỉ xuất hiện ở arr_a): [1 3 5 6]
Array arr_f (các phần tử có giá trị từ 5 đến 10 của arr_e): [ 6  9 10  8  6]


### Bài 3.4


In [4]:
import numpy as np

# 1. Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[5] = 1
print("Array arr_zeros:", arr_zeros)

# 2. Tạo arr_h có giá trị từ 10 đến 24, in danh sách các phần tử theo thứ tự đảo ngược
arr_h = np.arange(10, 25)
arr_h_reversed = arr_h[::-1]
print("Array arr_h:", arr_h)
print("Array arr_h đảo ngược:", arr_h_reversed)

# 3. Tạo arr_l từ arr_k với các phần tử khác 0
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = arr_k[arr_k != 0]
print("Array arr_l (các phần tử khác 0 của arr_k):", arr_l)

# 4. Thêm 2 phần tử có giá trị 10 và 20 vào cuối arr_l
arr_l = np.append(arr_l, [10, 20])
print("Array arr_l sau khi thêm 10 và 20:", arr_l)

# 5. Thêm phần tử có giá trị 100 vào vị trí có index = 5
arr_l = np.insert(arr_l, 5, 100)
print("Array arr_l sau khi thêm 100 vào vị trí 5:", arr_l)

# 6. Xóa các phần tử tại vị trí có index = 0, 1, 2
arr_l = np.delete(arr_l, [0, 1, 2])
print("Array arr_l sau khi xóa các phần tử ở vị trí 0, 1, 2:", arr_l)


Array arr_zeros: [0 0 0 0 0 1 0 0 0 0]
Array arr_h: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Array arr_h đảo ngược: [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Array arr_l (các phần tử khác 0 của arr_k): [1 2 8 2 1 3 5]
Array arr_l sau khi thêm 10 và 20: [ 1  2  8  2  1  3  5 10 20]
Array arr_l sau khi thêm 100 vào vị trí 5: [  1   2   8   2   1 100   3   5  10  20]
Array arr_l sau khi xóa các phần tử ở vị trí 0, 1, 2: [  2   1 100   3   5  10  20]


### Bài 3.5

In [5]:
import numpy as np

# Bước 1: Đọc dữ liệu từ file heights_1.txt và weights_1.txt
with open('heights_1.txt', 'r') as f:
    height = [float(line.strip()) for line in f]

with open('weights_1.txt', 'r') as f:
    weight = [float(line.strip()) for line in f]

# Bước 2: Tạo numpy array arr_height từ list height
arr_height = np.array(height)

# Bước 3: Tạo numpy array arr_weight từ list weight
arr_weight = np.array(weight)

# Bước 4: Chuyển đổi chiều cao sang mét
arr_height_m = arr_height * 0.0254

# Bước 5: Chuyển đổi cân nặng sang kg
arr_weight_kg = arr_weight * 0.453592

# Bước 6: Tính chỉ số BMI
arr_bmi = arr_weight_kg / (arr_height_m ** 2)

# Bước 7: Lấy giá trị cân nặng tại index = 50
weight_at_index_50 = arr_weight_kg[50]

# Bước 8: Lấy các phần tử từ index 100 đến 110 trong arr_height_m
arr_height_m_100 = arr_height_m[100:111]

# Bước 9: Lấy các cầu thủ có BMI < 21
players_bmi_below_21 = arr_bmi[arr_bmi < 21]

# Bước 10: Tính chiều cao trung bình và cân nặng trung bình
average_height = np.mean(arr_height_m)
average_weight = np.mean(arr_weight_kg)

# Bước 11: Tìm chiều cao và cân nặng lớn nhất
max_height = np.max(arr_height_m)
max_weight = np.max(arr_weight_kg)

# Bước 12: Tìm chiều cao và cân nặng nhỏ nhất
min_height = np.min(arr_height_m)
min_weight = np.min(arr_weight_kg)

# In kết quả
print("Array of Heights in meters:", arr_height_m)
print("Array of Weights in kg:", arr_weight_kg)
print("Array of BMI:", arr_bmi)
print("Weight at index 50:", weight_at_index_50)
print("Height from index 100 to 110:", arr_height_m_100)
print("Players with BMI < 21:", players_bmi_below_21)
print("Average height (m):", average_height)
print("Average weight (kg):", average_weight)
print("Maximum height (m):", max_height)
print("Maximum weight (kg):", max_weight)
print("Minimum height (m):", min_height)
print("Minimum weight (kg):", min_weight)

ValueError: could not convert string to float: '74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73,  73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72,  73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75,    73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72,    71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72,    72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73'

### Bài 3.6

In [6]:
import numpy as np

# 1. Tạo array art có kích thước 3x3 với các giá trị True
art = np.full((3, 3), True)
print("Array art:\n", art)

# 2. Tạo array arr_ID và tạo array 2 chiều arr_2D từ nó
arr_ID = np.array([0, 12345678, 0])  # Thêm một giá trị nữa để đủ 3 cột
arr_2D = np.tile(arr_ID, (3, 1))     # Tạo kích thước 3x3
print("\nArray arr_2D ban đầu:\n", arr_2D)

# Chuyển cột 1 sang cột 3 và ngược lại
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\nArray arr_2D sau khi đổi thứ tự cột:\n", arr_2D)


# 3. Chuyển dòng 1 sang dòng 2 và ngược lại
arr_2D[[0, 1]] = arr_2D[[1, 0]]
print("\nArray arr_2D sau khi đổi thứ tự dòng:\n", arr_2D)

# 4. Đảo ngược các dòng của arr_2D
arr_2D = arr_2D[::-1]
print("\nArray arr_2D sau khi đảo ngược các dòng:\n", arr_2D)

# 5. Đảo ngược các cột của arr_2D
arr_2D = arr_2D[:, ::-1]
print("\nArray arr_2D sau khi đảo ngược các cột:\n", arr_2D)

# 6. Kiểm tra giá trị null trong arr_2D_null
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()
print("\nArray arr_2D_null:\n", arr_2D_null)
print("Có giá trị null trong arr_2D_null không?", has_nan)

# 7. Thay thế giá trị null bằng 0
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\nArray arr_2D_null sau khi thay thế giá trị null bằng 0:\n", arr_2D_null)

Array art:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

Array arr_2D ban đầu:
 [[       0 12345678        0]
 [       0 12345678        0]
 [       0 12345678        0]]

Array arr_2D sau khi đổi thứ tự cột:
 [[       0 12345678        0]
 [       0 12345678        0]
 [       0 12345678        0]]

Array arr_2D sau khi đổi thứ tự dòng:
 [[       0 12345678        0]
 [       0 12345678        0]
 [       0 12345678        0]]

Array arr_2D sau khi đảo ngược các dòng:
 [[       0 12345678        0]
 [       0 12345678        0]
 [       0 12345678        0]]

Array arr_2D sau khi đảo ngược các cột:
 [[       0 12345678        0]
 [       0 12345678        0]
 [       0 12345678        0]]


AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

### Bài 3.7


In [7]:
import numpy as np

# 1. Đọc dữ liệu từ tập tin vào danh sách baseball
with open('baseball_2D.txt', 'r') as file:
    baseball = [list(map(float, line.strip().split())) for line in file]

# Tạo mảng numpy 2D từ baseball
np_baseball = np.array(baseball)

# Kiểm tra kiểu dữ liệu và kích thước của np_baseball
print("Dữ liệu np_baseball:\n", np_baseball)
print("Kiểu dữ liệu của np_baseball:", np_baseball.dtype)
print("Kích thước của np_baseball:", np_baseball.shape)

# 2. In các giá trị của dòng thứ 50 trong np_baseball
print("\nDòng thứ 50 trong np_baseball:", np_baseball[49])

# 3. Tạo numpy array np_weight từ cột hai của np_baseball
np_weight = np_baseball[:, 1]
print("\nMảng np_weight (cột cân nặng):\n", np_weight)

# 4. Chiều cao của vận động viên thứ 124
print("\nChiều cao của vận động viên thứ 124:", np_baseball[123, 0])

# 5. Tính chiều cao trung bình và cân nặng trung bình của các cầu thủ
mean_height = np.mean(np_baseball[:, 0])
mean_weight = np.mean(np_baseball[:, 1])
print("\nChiều cao trung bình của các cầu thủ:", mean_height)
print("Cân nặng trung bình của các cầu thủ:", mean_weight)

# 6. Tính tương quan giữa chiều cao và cân nặng
correlation = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])[0, 1]
print("\nHệ số tương quan giữa chiều cao và cân nặng của các cầu thủ:", correlation)

# Nhận xét về mối tương quan
if correlation > 0:
    print("Nhận xét: Chiều cao và cân nặng có mối tương quan thuận.")
elif correlation < 0:
    print("Nhận xét: Chiều cao và cân nặng có mối tương quan nghịch.")
else:
    print("Nhận xét: Chiều cao và cân nặng không có mối tương quan.")

FileNotFoundError: [Errno 2] No such file or directory: 'baseball_2D.txt'

### Bài 3.8

In [ ]:
import numpy as np

# 1. Đọc dữ liệu từ hai tệp heights.txt và positions.txt
with open('heights.txt', 'r') as file:
    heights = [float(line.strip()) for line in file]

with open('positions.txt', 'r') as file:
    positions = [line.strip() for line in file]

# a) Tạo numpy array np_positions từ list positions
np_positions = np.array(positions)
print("Dữ liệu np_positions:\n", np_positions)
print("Kiểu dữ liệu của np_positions:", np_positions.dtype)

# b) Tạo numpy array np_heights từ list heights
np_heights = np.array(heights)
print("\nDữ liệu np_heights:\n", np_heights)
print("Kiểu dữ liệu của np_heights:", np_heights.dtype)

# 2. Tính chiều cao trung bình của các GK
gk_heights = np_heights[np_positions == 'GK']
mean_gk_height = np.mean(gk_heights)
print("\nChiều cao trung bình của các GK:", mean_gk_height)

# 3. Tính chiều cao trung bình của những vị trí khác (Không phải là GK)
non_gk_heights = np_heights[np_positions != 'GK']
mean_non_gk_height = np.mean(non_gk_heights)
print("Chiều cao trung bình của những vị trí khác (Không phải GK):", mean_non_gk_height)

# 4. Tạo mảng dữ liệu có cấu trúc tự định nghĩa players
players = np.array(list(zip(np_positions, np_heights)), dtype=[('position', 'U5'), ('height', 'float')])
print("\nMảng players:\n", players)

# 5. Sắp mảng players theo chiều cao, tìm vị trí có chiều cao cao nhất và thấp nhất
sorted_players = np.sort(players, order='height')
print("\nMảng players sau khi sắp xếp theo height:\n", sorted_players)
print("\nVị trí có chiều cao thấp nhất:", sorted_players[0]['position'], "- Chiều cao:", sorted_players[0]['height'])
print("Vị trí có chiều cao cao nhất:", sorted_players[-1]['position'], "- Chiều cao:", sorted_players[-1]['height'])

### Bài 3.9


In [ ]:
import pandas as pd

# Tạo data frame từ tệp CSV
euro12 = pd.read_csv('euro2012.csv')

# In kiểu dữ liệu, kích thước và danh sách các cột
print("Kiểu dữ liệu của euro12:", type(euro12))
print("Kích thước của euro12:", euro12.shape)
print("Danh sách các cột của euro12:", euro12.columns.tolist())

# 1. In giá trị cột Goals
print("\nCột Goals:\n", euro12['Goals'])

# 2. Có bao nhiêu đội tham gia Euro 2012?
num_teams = euro12['Team'].nunique()
print("\nSố đội tham gia Euro 2012:", num_teams)

# 3. In thông tin của Euro 2012
print("\nThông tin của Euro 2012:")
print(euro12.info())

# 4. Tạo data frame mới từ euro12 tên là discipline chỉ chứa các cột "Team", "Yellow Cards", "Red Cards"
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
print("\nDataFrame discipline:\n", discipline)

# 5. Sắp xếp discipline giảm dần theo 'Red Cards', 'Yellow Cards'
discipline_sorted = discipline.sort_values(by=['Red Cards', 'Yellow Cards'], ascending=False)
print("\nDataFrame discipline sau khi sắp xếp:\n", discipline_sorted)

# 6a. Tính trung bình số thẻ vàng (Yellow Cards)
mean_yellow_cards = euro12['Yellow Cards'].mean()
print("\nTrung bình số thẻ vàng:", mean_yellow_cards)

# 6b. Lọc các đội đã ghi hơn 6 bàn thắng
teams_more_than_6_goals = euro12[euro12['Goals'] > 6]
print("\nCác đội đã ghi hơn 6 bàn thắng:\n", teams_more_than_6_goals[['Team', 'Goals']])

# 7. In các đội mà tên bắt đầu bằng 'G'
teams_start_with_G = euro12[euro12['Team'].str.startswith('G')]
print("\nCác đội có tên bắt đầu bằng 'G':\n", teams_start_with_G[['Team']])

# 8. In 7 cột đầu của euro12
print("\n7 cột đầu của euro12:\n", euro12.iloc[:, :7])

# 9. In tất cả các cột, trừ 3 cột cuối
print("\nTất cả các cột trừ 3 cột cuối:\n", euro12.iloc[:, :-3])

# 10. In các cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards
print("\nCác cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards:\n",
      euro12[['Team', 'Goals', 'Shooting Accuracy', 'Yellow Cards', 'Red Cards']])

# 11. In các cột 'Team', 'Shooting Accuracy' từ các đội 'England', 'Italy', 'Russia'
selected_teams = euro12[euro12['Team'].isin(['England', 'Italy', 'Russia'])]
print("\nCác cột 'Team', 'Shooting Accuracy' từ các đội 'England', 'Italy', 'Russia':\n",
      selected_teams[['Team', 'Shooting Accuracy']])